global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'co'
    static_configs:
      - targets: ['host.docker.internal:9200']
  - job_name: 'lo'
    static_configs:
      - targets: ['host.docker.internal:9201']
  - job_name: 'en'
    static_configs:
      - targets: ['host.docker.internal:9210']
