server:
  port: 8080
  name: "central orchestrator"
  site: site_id_1
  # site: f95d34b2-8019-4590-a3ff-ff1e15ecc5d5 
git:
  owner: edge-orchestration-platform
  repo: deployments
  branch: main
  private: true
  token_env: GITHUB_TOKEN
appregistry:
  repo: https://github.com/edge-orchestration-platform/app-registry
  branch: main
mode: push
# nats:
#   url: nats://localhost:4222

