server:
  port: 9101
  name: "central orchestrator"
  site: f95d34b2-8019-4590-a3ff-ff1e15ecc5d5 
  # interval: 30s
  # repo_owner: edge-orchestration-platform
  # repo_name: deployments
  # yaml_path: site-1/com-balaji-compose-a/desiredstate.yaml

git:
  owner: edge-orchestration-platform
  repo: deployments
  branch: main
  private: true
  token_env: GITHUB_TOKEN
appregistry:
  repo: https://github.com/edge-orchestration-platform/app-registry
  branch: main
mode: push
nats:
  url: nats://localhost:4222

