server:
  port: 9102
  site: f95d34b2-8019-4590-a3ff-ff1e15ecc5d5
database:
  url: postgres://postgres:postgres@postgres:5432/orchestration?sslmode=disable 
mode: pull
nats:
  url: nats://nats:4222
poll_interval_seconds: 20
git:
  repo: https://github.com/edge-orchestration-platform/deployments.git
  path_filter: sites/tiruvannamalai/desiredstate.yaml
co:
  url: http://co:9101/api/v1
  

