server:
  port: 9102
  site: ef155d81-7753-4484-86e6-abc904b8c141
database:
  url: postgres://postgres:postgres@localhost:5432/orchestration?sslmode=disable 
mode: push
nats:
  url: nats://localhost:4222
git:
  path_filter: sites/chennai/desiredstate.yaml


